import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/Sidebar/Sidebar";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add the required font weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={`font-poppins flex h-full antialiased bg-primary-100`}>
        <SideBar />
        <div className="w-full max-h-screen bg-primary-50 rounded-l-[60px] overflow-auto p-[50px]">
          {children}
        </div>
      </body>
    </html>
  );
}
